# Generated by Django 4.2 on 2023-04-27 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 27, 16, 22, 16, 362934, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
