# Generated by Django 4.2 on 2023-04-18 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 18, 15, 0, 16, 129942, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
